website/auth.py
# Here will be all the routes for the authentication

from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/')
def main():
    return render_template('main.html')

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Loggged in Successfully!!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect Password, try again!!', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template('login.html', user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exist', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 4 characters.', category='error')
        elif len(name) < 2:
            flash('Name must be greater than 2 characters.', category='error')
        elif password1 != password2:
            flash('Passwords do not match.', category='error')
        elif len(password1) < 7:
            flash('Password must be greater than 7.', category='error')
        else:
            new_user = User(name=name, email=email, password=generate_password_hash(password1, method='sha256')) # This is model
            #add user to the database.
            db.session.add(new_user)
            db.session.commit()
            flash('Account Added', category='success')
            return redirect(url_for('auth.login'))  # blueprintName.FxnName

    return render_template("sign_up.html")

website/views.py
# Here i will be storing the routes(location) of my website visible to the user

from flask import Blueprint, render_template, flash, request, jsonify
from flask_login import login_required, current_user
from .models import Diabetes, User, Heart, BCancer, Liver, User
from . import db
import pickle
import pandas as pd
import numpy as np

import sys
import os
import glob
import re
from werkzeug.utils import secure_filename

# Keras
from PIL import Image
from tensorflow.keras.applications.imagenet_utils import preprocess_input, decode_predictions
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

views = Blueprint('views', __name__)

@views.route("/home", methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home2.html")


@views.route("/diabetes", methods=['GET', 'POST'])
@login_required
def diabetes():
    if request.method == 'GET':
        return render_template('diabetes_pred.html')
    else:
        Pregnancies = int(request.form['Pregnancies'])
        Glucose = int(request.form['Glucose'])
        BloodPressure = int(request.form['BloodPressure'])
        SkinThickness = int(request.form['SkinThickness'])
        Insulin = int(request.form['Insulin'])
        BMI = float(request.form['BMI'])
        DiabetesPedigreeFunction = float(request.form['DiabetesPedigreeFunction'])
        Age = int(request.form['Age'])

        model1 = pickle.load(open('model/diabetes_final_model.pkl','rb'))
        input_data = (Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age)
        input_data_as_numpy_array= np.asarray(input_data)
        input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
        print(input_data_reshaped)
        prediction = model1.predict(input_data_reshaped)
        senddata=""
        predi = ""
        print(prediction[0])
        if (prediction[0] == 0):
            senddata='According to the given details person does not have Diabetes'
            predi = "Not Diabetic"
        else:
            senddata='According to the given details chances of having Diabetes are High, So Please Consult a Doctor'
            predi = "Diabetic"
            
        new_data = Diabetes(pregnancies=Pregnancies, 
                                glucose=Glucose,
                                bloodpressure=BloodPressure,
                                skinthichness=SkinThickness,
                                insulin=Insulin,
                                bmi=BMI,
                                dpf=DiabetesPedigreeFunction,
                                age=Age,
                                outcome=predi,
                                user_id=current_user.id)
        db.session.add(new_data)
        db.session.commit()

        return render_template('diabetes_pred.html', prediction_text=senddata)

@views.route("/diabetes_history")
@login_required
def diabetes_history():
    return render_template('diabetes_history.html', user=current_user)


@views.route("/heart", methods=['GET', 'POST'])
@login_required
def heart():
    if request.method == 'GET':
        return render_template('heart_pred.html')
    else:
        age = int(request.form['age'])
        sex = int(request.form['sex'])
        cp = int(request.form['cp'] )
        trestbps = int(request.form['trestbps'])
        chol = int(request.form['chol'])
        fbs = int(request.form['fbs'])
        restecg = int(request.form['restecg'])
        thalach = int(request.form['thalach'])
        exang = int(request.form['exang'])
        oldpeak = float(request.form['oldpeak'])
        slope = int(request.form['slope']) 
        ca = int(request.form['ca'])
        thal= int(request.form['thal'])

        if sex == 1:
            gender="Male"
        else:
            gender="Female"

        model_heart = pickle.load(open('model/heart_final_model.pkl', 'rb'))
        input_data = (age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal)

        print(input_data)

        input_data_as_numpy_array= np.asarray(input_data)
        input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
        print(input_data_reshaped)
        
        prediction = model_heart.predict(input_data_reshaped)
        senddata=""
        if (prediction[0]== 0):
            predi="No Heart Disease"
            senddata='According to the given details person does not have any Heart Diesease.'
        else:
            predi="Heart Disease"
            senddata='According to the given details chances of having Heart Diesease are High, So Please Consult a Doctor'

        new_data = Heart(age=age,
                        sex=gender,
                        cp=cp,
                        trestbps=trestbps,
                        chol=chol,
                        fbs=fbs,
                        restecg=restecg,
                        thalach=thalach,
                        exang=exang,
                        oldpeak=oldpeak,
                        slope=slope,
                        ca=ca,
                        thal=thal,
                        outcome=predi,
                        user_id=current_user.id)
        db.session.add(new_data)
        db.session.commit()

        return render_template('heart_pred.html', prediction_text=senddata)

@views.route("/heart_history")
@login_required
def heart_history():
    return render_template('heart_history.html', user=current_user)

@views.route("/bcancer", methods=['GET', 'POST'])
@login_required
def bcancer():
    if request.method == 'GET':
        return render_template('cancer_pred.html')
    else: 
        radius_mean = float(request.form['radius_mean'])
        texture_mean = float(request.form['texture_mean']) 
        perimeter_mean = float(request.form['perimeter_mean'])
        area_mean = float(request.form['area_mean']) 
        smoothness_mean = float(request.form['smoothness_mean']) 
        compactness_mean = float(request.form['compactness_mean']) 
        concavity_mean = float(request.form['concavity_mean'])
        concave_points_mean = float(request.form['concave_points_mean']) 
        symmetry_mean = float(request.form['symmetry_mean']) 
        fractal_dimension_mean = float(request.form['fractal_dimension_mean'])
        radius_se = float(request.form['radius_se']) 
        texture_se = float(request.form['texture_se']) 
        perimeter_se = float(request.form['perimeter_se']) 
        area_se = float(request.form['area_se']) 
        smoothness_se = float(request.form['smoothness_se'])
        compactness_se = float(request.form['compactness_se']) 
        concavity_se = float(request.form['concavity_se']) 
        concave_points_se = float(request.form['concave_points_se']) 
        symmetry_se = float(request.form['symmetry_se'])
        fractal_dimension_se = float(request.form['fractal_dimension_se']) 
        radius_worst = float(request.form['radius_worst']) 
        texture_worst = float(request.form['texture_worst'])
        perimeter_worst = float(request.form['perimeter_worst']) 
        area_worst = float(request.form['area_worst']) 
        smoothness_worst = float(request.form['smoothness_worst'])
        compactness_worst = float(request.form['compactness_worst']) 
        concavity_worst = float(request.form['concavity_worst']) 
        concave_points_worst = float(request.form['concave_points_worst'])
        symmetry_worst = float(request.form['symmetry_worst']) 
        fractal_dimension_worst = float(request.form['fractal_dimension_worst'])

        model_bcancer = pickle.load(open('model/cancer_final_model.pkl', 'rb'))
        input_data = (radius_mean, texture_mean, perimeter_mean,
                    area_mean, smoothness_mean, compactness_mean, concavity_mean,
                    concave_points_mean, symmetry_mean, fractal_dimension_mean,
                    radius_se, texture_se, perimeter_se, area_se, smoothness_se,
                    compactness_se, concavity_se, concave_points_se, symmetry_se,
                    fractal_dimension_se, radius_worst, texture_worst,
                    perimeter_worst, area_worst, smoothness_worst,
                    compactness_worst, concavity_worst, concave_points_worst,
                    symmetry_worst, fractal_dimension_worst)

        print(input_data)

        input_data_as_numpy_array= np.asarray(input_data)
        input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
        print(input_data_reshaped)

        prediction = model_bcancer.predict(input_data_reshaped)
        senddata=""
        if (prediction[0] == 0):
            prediction = model_bcancer.predict_proba(input_data_reshaped)[:, 0]
            y_prob=round(prediction[0], 3)
            y_prob=y_prob*100
            predi = "Benign"
            senddata='According to the given details the patient have a chance of Benign Type Cancer with the accuracy of '
        else:
            prediction = model_bcancer.predict_proba(input_data_reshaped)[:, 1]
            y_prob=round(prediction[0], 3)
            y_prob=y_prob*100
            predi = "Malignant"
            senddata='According to the given details the patient have a chance of Malignant Type Cancer with the accuracy of'

        new_data = BCancer(radius_mean=radius_mean,
                        texture_mean=texture_mean, 
                        perimeter_mean=perimeter_mean,
                        area_mean=area_mean,
                        smoothness_mean=smoothness_mean,
                        compactness_mean=compactness_mean, 
                        concavity_mean=concavity_mean,
                        concave_points_mean=concave_points_mean, 
                        symmetry_mean=symmetry_mean, 
                        fractal_dimension_mean=fractal_dimension_mean,
                        outcome=predi,
                        user_id=current_user.id)
        db.session.add(new_data)
        db.session.commit()

website/templates/base.html
    {% include "navbar.html" %}

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger after-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" area-label="Close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}">
    </script>
</body>

</html>

website/templates/bases.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HDS</title>
    <link href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">      
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav mr-auto">
                <a href="/home" class="nav-item nav-link" id="home">Home</a>
            </div>
            <div class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Diabetes
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/diabetes">Make Prediction</a>
                      <a class="dropdown-item" href="/diabetes_history">History</a>
                  </li>
    
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Heart
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/heart">Make Prediction</a>
                      <a class="dropdown-item" href="/heart_history">History</a>
                  </li>
    
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Breast Cancer
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/bcancer">Make Prediction</a>
                      <a class="dropdown-item" href="/bcancer_history">History</a>
                  </li>
    
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Liver Disease
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/liver">Make Prediction</a>
                      <a class="dropdown-item" href="/liver_history">History</a>
                  </li>
                  <div class="collapse navbar-collapse" id="navbar">
                    <div class="navbar-nav mr-auto">
                        <a href="/malaria" class="nav-item nav-link" id="home">Malaria</a>
                    </div>
                <a href="/logout" class="nav-item nav-link" id="logout">Logout</a>
            </div>
        </div>
    </nav>
    <div class="container">
        <div id="content" style="margin-top:2em">{% block content %}{% endblock %}</div>
    </div>
</body>

<footer>
    <script src="{{ url_for('static', filename='main.js') }}" type="text/javascript"></script>    
</footer>

</html>

website/templates/diabetes_pred.html
{% include "nav(logged).html" %}


<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/w3.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/blue.css') }}">
<body>
  <h1>Diabates Prediction</h1>

  <!-- Main Input For Receiving Query to our ML -->
  <div class="w3-container">
    <form action="{{ url_for('views.diabetes')}}" method="post">
      <input type="number" class="w3-input" name="Pregnancies" placeholder="Pregnancies" required="required" />
      <input type="number" class="w3-input" name="Glucose" placeholder="Glucose Level" required="required" />
      <input type="number" class="w3-input" name="BloodPressure" placeholder="Blood Pressure Level" required="required" />
      <input type="number" class="w3-input" name="SkinThickness" placeholder="Skin Thickness" required="required" />
      <input type="number" class="w3-input" name="Insulin" placeholder="Insulin Level" required="required" />
      <input type="number" step="any" class="w3-input" name="BMI" placeholder="Body Mass Index" required="required" />
      <input type="number" step="any" class="w3-input" name="DiabetesPedigreeFunction" placeholder="Diabetes Pedigree Function" required="required">
      <input type="number" class="w3-input" name="Age" placeholder="Enter Age" required="required"><br>
      <button type="submit" class="w3-border-red w3-round-large w3-center w3-indigo w3-button w3-btn w3-animate-bottom">Predict</button>
    </form>
  </div>

  <br>
  <div class="container w3-number-white">
    <h3>Output</h3>
    <br>
    <h2>
      {{ prediction_text }}<br>
    </h2>
    <br>
  </div>
</body>
<script>
  $(document).ready(function () {
    $('#dtDynamicVerticalScrollExample').DataTable({
      "scrollY": "50vh",
      "scrollCollapse": true,
    });
    $('.dataTables_length').addClass('bs-select');
  });
</script>
</head>

website/templates/login.html
{% extends 'base_1.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<form action="" method="post">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" name="email" id="email" class="form-control" placeholder="Enter email" required><br>
    
        <label for="password1">Enter Password</label>
        <input type="password" name="password" id="password" class="form-control" placeholder="Enter password" required><br>
    
        <button type="submit" class="btn btn-primary">Login</button>

    </div>
</form>
{% endblock %}

website/templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/w3.css') }}"> -->
   <style>
    .lefty{
        text-align: left;
    }
   </style>
</head>

<body>
    <div class="body">
        <header>
            <img src="{{ url_for('static', filename='css/hds.png') }}" alt="" class="banner">
            <!-- <a href="#" class="logo">HDS</a> -->
            <div class="toggle"></div>
            <nav>
                <ul>
                    <li><a class="lefty" href="#" style="
                        padding-right: 886px;
                        padding-top: 22px;
                        "> 
                        <img src="{{ url_for('static', filename='css/Black Simple Monoline Real Estate Service Logo (1).gif') }}" height="50" alt=""></a></li>  
                </ul>
                <ul>
                    <li><a href="{{url_for('auth.main')}}" style="padding-top: 30px;">Home</a></li>
                    <li><a href="{{url_for('auth.login')}}" style="padding-top: 30px;">Login</a></li>
                    <li><a href="{{url_for('auth.sign_up')}}" style="padding-top: 30px;">Register</a></li>
                </ul>
            </nav>
        </header>
        <script>
            window.addEventListener("scroll", function () {
                const header = document.querySelector('header');
                header.classList.toggle('sticky', window.scrollY > 0);
            });
            const navigation = document.querySelector('nav');
            document.querySelector('.toggle').onclick = function () {
                this.classList.toggle('active');
                navigation.classList.toggle('active');
            }
        </script>
    </div>
</body>

</html>

website/templates/register.html
<html>
    <head>
        <style>
            *,
*:before,
*:after {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: 'Open Sans', Helvetica, Arial, sans-serif;
    background: #ffffff;
    background-image: url('img1.jpg');
}

input,
button {
    border: none;
    outline: none;
    background: none;
    font-family: 'Open Sans', Helvetica, Arial, sans-serif;
}

.tip {
    font-size: 20px;
    margin: 40px auto 50px;
    text-align: center;
}

.cont {
    border-radius: 20px;
    overflow: hidden;
    position: relative;
    width: 900px;
    height: 550px;
    margin: 0 auto 100px;
    background: #fff;
    box-shadow: -10px -10px 15px rgba(255, 255, 255, 0.3), 10px 10px 15px rgba(70, 70, 70, 0.15), inset -10px -10px 15px rgba(255, 255, 255, 0.3), inset 10px 10px 15px rgba(70, 70, 70, 0.15);
}

.form {
    position: relative;
    width: 640px;
    height: 100%;
    -webkit-transition: -webkit-transform 1.2s ease-in-out;
    transition: -webkit-transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out, -webkit-transform 1.2s ease-in-out;
    padding: 50px 30px 0;
}

.sub-cont {
    overflow: hidden;
    position: absolute;
    left: 640px;
    top: 0;
    width: 900px;
    height: 100%;
    padding-left: 260px;
    background: #fff;
    -webkit-transition: -webkit-transform 1.2s ease-in-out;
    transition: -webkit-transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out, -webkit-transform 1.2s ease-in-out;
}

.cont.s--signup .sub-cont {
    -webkit-transform: translate3d(-640px, 0, 0);
    transform: translate3d(-640px, 0, 0);
}

button {
    display: block;
    margin: 0 auto;
    width: 260px;
    height: 36px;
    border-radius: 30px;
    color: #fff;
    font-size: 15px;
    cursor: pointer;
}

.img {
    overflow: hidden;
    z-index: 2;
    position: absolute;
    left: 0;
    top: 0;
    width: 260px;
    height: 100%;
    padding-top: 360px;
}

.img:before {
    content: '';
    position: absolute;
    right: 0;
    top: 0;
    width: 900px;
    height: 100%;
    background-image: url("ext.jpg");
    opacity: .8;
    background-size: cover;
    -webkit-transition: -webkit-transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out, -webkit-transform 1.2s ease-in-out;
}

.img:after {
    content: '';
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.6);
}

.cont.s--signup .img:before {
    -webkit-transform: translate3d(640px, 0, 0);
    transform: translate3d(640px, 0, 0);
}

.img__text {
    z-index: 2;
    position: absolute;
    left: 0;
    top: 50px;
    width: 100%;
    padding: 0 20px;
    text-align: center;
    color: #fff;
    -webkit-transition: -webkit-transform 1.2s ease-in-out;
    transition: -webkit-transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out, -webkit-transform 1.2s ease-in-out;
}

.img__text h2 {
    margin-bottom: 10px;
    font-weight: normal;
}

.img__text p {
    font-size: 14px;
    line-height: 1.5;
}

.cont.s--signup .img__text.m--up {
    -webkit-transform: translateX(520px);
    transform: translateX(520px);
}

.img__text.m--in {
    -webkit-transform: translateX(-520px);
    transform: translateX(-520px);
}

.cont.s--signup .img__text.m--in {
    -webkit-transform: translateX(0);
    transform: translateX(0);
}

.img__btn {
    overflow: hidden;
    z-index: 2;
    position: relative;
    width: 100px;
    height: 36px;
    margin: 0 auto;
    background: transparent;
    color: #fff;
    text-transform: uppercase;
    font-size: 15px;
    cursor: pointer;
}

.img__btn:after {
    content: '';
    z-index: 2;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    border: 2px solid #fff;
    border-radius: 30px;
}

.img__btn span {
    position: absolute;
    left: 0;
    top: 0;
    display: -webkit-box;
    display: flex;
    -webkit-box-pack: center;
    justify-content: center;
    -webkit-box-align: center;
    align-items: center;
    width: 100%;
    height: 100%;
    -webkit-transition: -webkit-transform 1.2s;
    transition: -webkit-transform 1.2s;
    transition: transform 1.2s;
    transition: transform 1.2s, -webkit-transform 1.2s;
}

.img__btn span.m--in {
    -webkit-transform: translateY(-72px);
    transform: translateY(-72px);
}

.cont.s--signup .img__btn span.m--in {
    -webkit-transform: translateY(0);
    transform: translateY(0);
}

.cont.s--signup .img__btn span.m--up {
    -webkit-transform: translateY(72px);
    transform: translateY(72px);
}

h2 {
    width: 100%;
    font-size: 26px;
    text-align: center;
}

label {
    display: block;
    width: 260px;
    margin: 25px auto 0;
    text-align: center;
}

label span {
    font-size: 12px;
    color: #cfcfcf;
    text-transform: uppercase;
}

input {
    display: block;
    width: 100%;
    margin-top: 5px;
    padding-bottom: 5px;
    font-size: 16px;
    border-bottom: 1px solid rgba(0, 0, 0, 0.4);
    text-align: center;
}

.forgot-pass {
    margin-top: 15px;
    text-align: center;
    font-size: 12px;
    color: #cfcfcf;
}

.submit {
    margin-top: 40px;
    margin-bottom: 20px;
    background: #d4af7a;
    text-transform: uppercase;
}

.fb-btn {
    border: 2px solid #d3dae9;
    color: #8fa1c7;
}

.fb-btn span {
    font-weight: bold;
    color: #455a81;
}

.sign-in {
    -webkit-transition-timing-function: ease-out;
    transition-timing-function: ease-out;
}

.cont.s--signup .sign-in {
    -webkit-transition-timing-function: ease-in-out;
    transition-timing-function: ease-in-out;
    -webkit-transition-duration: 1.2s;
    transition-duration: 1.2s;
    -webkit-transform: translate3d(640px, 0, 0);
    transform: translate3d(640px, 0, 0);
}

.sign-up {
    -webkit-transform: translate3d(-900px, 0, 0);
    transform: translate3d(-900px, 0, 0);
}

.cont.s--signup .sign-up {
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
}
        </style>
    </head>
    <body>
        <br>
<br>
    <div class="cont">a
        <div class="form sign-in">
            <h2>Welcome</h2>
            <label>
                <span>Email</span>
                <input type="email" />
            </label>
            <label>
                <span>Password</span>
                <input type="password" />
            </label>
            <p class="forgot-pass">Forgot password?</p>
            <button type="button" class="submit">Sign In</button>
         
        </div>
        <div class="sub-cont">
            <div class="img">
                <div class="img__text m--up">
                 
                    <h3>Don't have an account? Please Sign up!<h3>
                </div>
                <div class="img__text m--in">
                
                    <h3>If you already has an account, just sign in.<h3>
                </div>
                <div class="img__btn">
                    <span class="m--up">Sign Up</span>
                    <span class="m--in">Sign In</span>
                </div>
            </div>



            {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger after-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="'true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

            <div class="form sign-up">
                <h2>Create your Account</h2>
                <form action="{{ url_for('auth.sign_up')}}" method="post">
                    <label>
                        <span>Name</span>
                        <input type="text" name="firstName" id="firstName" class="form-control"/>
                    </label>
                    <label>
                        <span>Email</span>
                        <input type="email" name="email" id="email" class="form-control"/>
                    </label>
                    <label>
                        <span>Password</span>
                        <input type="password" name="password1" id="password1" class="form-control"/>
                    </label>
                    <label>
                        <span>Confirm Password</span>
                        <input type="password" name="password2" id="password2" class="form-control" class="form-control"/>
                    </label>
                    <button type="submit" class="submit">Sign Up</button>    
                </form>
            </div>
        </div>
    </div>

    <script>
        document.querySelector('.img__btn').addEventListener('click', function() {
            document.querySelector('.cont').classList.toggle('s--signup');
        });
    </script>
    </body>
</html>